# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p_count_pro_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_p_count_pro_fee(object):
    def setupUi(self, p_count_pro_fee):
        p_count_pro_fee.setObjectName("p_count_pro_fee")
        p_count_pro_fee.resize(400, 300)
        self.label = QtWidgets.QLabel(p_count_pro_fee)
        self.label.setGeometry(QtCore.QRect(50, 60, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(p_count_pro_fee)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 21, 16))
        self.label_2.setObjectName("label_2")
        self.year_lineEdit = QtWidgets.QLineEdit(p_count_pro_fee)
        self.year_lineEdit.setGeometry(QtCore.QRect(100, 60, 113, 21))
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.month_lineEdit = QtWidgets.QLineEdit(p_count_pro_fee)
        self.month_lineEdit.setGeometry(QtCore.QRect(100, 120, 113, 21))
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.label_3 = QtWidgets.QLabel(p_count_pro_fee)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(p_count_pro_fee)
        self.label_4.setGeometry(QtCore.QRect(150, 170, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(p_count_pro_fee)
        self.label_5.setGeometry(QtCore.QRect(260, 170, 72, 15))
        self.label_5.setObjectName("label_5")
        self.due_pay_lineEdit = QtWidgets.QLineEdit(p_count_pro_fee)
        self.due_pay_lineEdit.setGeometry(QtCore.QRect(20, 210, 71, 21))
        self.due_pay_lineEdit.setObjectName("due_pay_lineEdit")
        self.paid_lineEdit = QtWidgets.QLineEdit(p_count_pro_fee)
        self.paid_lineEdit.setGeometry(QtCore.QRect(130, 210, 81, 21))
        self.paid_lineEdit.setObjectName("paid_lineEdit")
        self.not_paid_lineEdit = QtWidgets.QLineEdit(p_count_pro_fee)
        self.not_paid_lineEdit.setGeometry(QtCore.QRect(240, 210, 81, 21))
        self.not_paid_lineEdit.setObjectName("not_paid_lineEdit")
        self.pushButton = QtWidgets.QPushButton(p_count_pro_fee)
        self.pushButton.setGeometry(QtCore.QRect(130, 267, 91, 21))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(p_count_pro_fee)
        QtCore.QMetaObject.connectSlotsByName(p_count_pro_fee)

    def retranslateUi(self, p_count_pro_fee):
        _translate = QtCore.QCoreApplication.translate
        p_count_pro_fee.setWindowTitle(_translate("p_count_pro_fee", "p_count_pro_fee"))
        self.label.setText(_translate("p_count_pro_fee", "年"))
        self.label_2.setText(_translate("p_count_pro_fee", "月"))
        self.label_3.setText(_translate("p_count_pro_fee", "应缴"))
        self.label_4.setText(_translate("p_count_pro_fee", "已缴"))
        self.label_5.setText(_translate("p_count_pro_fee", "未缴"))
        self.pushButton.setText(_translate("p_count_pro_fee", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    p_count_pro_fee = QtWidgets.QWidget()
    ui = Ui_p_count_pro_fee()
    ui.setupUi(p_count_pro_fee)
    p_count_pro_fee.show()
    sys.exit(app.exec_())
