# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parking_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parking_fee(object):
    def setupUi(self, parking_fee):
        parking_fee.setObjectName("parking_fee")
        parking_fee.resize(517, 394)
        self.widget = QtWidgets.QWidget(parking_fee)
        self.widget.setGeometry(QtCore.QRect(240, 70, 215, 85))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.new_pushButton = QtWidgets.QPushButton(self.widget)
        self.new_pushButton.setObjectName("new_pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.new_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(self.widget)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.exit_pushButton)
        self.is_paid_label = QtWidgets.QLabel(parking_fee)
        self.is_paid_label.setGeometry(QtCore.QRect(240, 180, 231, 91))
        self.is_paid_label.setText("")
        self.is_paid_label.setObjectName("is_paid_label")
        self.widget_2 = QtWidgets.QWidget(parking_fee)
        self.widget_2.setGeometry(QtCore.QRect(40, 20, 193, 330))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.year_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.year_lineEdit.setReadOnly(True)
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.verticalLayout.addWidget(self.year_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.month_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.month_lineEdit.setReadOnly(True)
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.verticalLayout.addWidget(self.month_lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.due_payment_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.due_payment_lineEdit.setReadOnly(True)
        self.due_payment_lineEdit.setObjectName("due_payment_lineEdit")
        self.verticalLayout.addWidget(self.due_payment_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.paid_dateEdit = QtWidgets.QDateEdit(self.widget_2)
        self.paid_dateEdit.setObjectName("paid_dateEdit")
        self.verticalLayout.addWidget(self.paid_dateEdit)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.staff_id_lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.staff_id_lineEdit.setReadOnly(True)
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.verticalLayout.addWidget(self.staff_id_lineEdit)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.parking_id_comboBox = QtWidgets.QComboBox(self.widget_2)
        self.parking_id_comboBox.setObjectName("parking_id_comboBox")
        self.verticalLayout.addWidget(self.parking_id_comboBox)

        self.retranslateUi(parking_fee)
        self.exit_pushButton.clicked.connect(parking_fee.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(parking_fee)

    def retranslateUi(self, parking_fee):
        _translate = QtCore.QCoreApplication.translate
        parking_fee.setWindowTitle(_translate("parking_fee", "parking_fee"))
        self.pushButton.setText(_translate("parking_fee", "缴费"))
        self.new_pushButton.setText(_translate("parking_fee", "刷新"))
        self.exit_pushButton.setText(_translate("parking_fee", "退出"))
        self.label.setText(_translate("parking_fee", "年"))
        self.label_2.setText(_translate("parking_fee", "月"))
        self.label_3.setText(_translate("parking_fee", "应付停车费"))
        self.label_5.setText(_translate("parking_fee", "付费时间"))
        self.label_6.setText(_translate("parking_fee", "员工_id"))
        self.label_4.setText(_translate("parking_fee", "车位号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    parking_fee = QtWidgets.QWidget()
    ui = Ui_parking_fee()
    ui.setupUi(parking_fee)
    parking_fee.show()
    sys.exit(app.exec_())
