# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'property_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_property_fee(object):
    def setupUi(self, property_fee):
        property_fee.setObjectName("property_fee")
        property_fee.resize(550, 375)
        self.label_2 = QtWidgets.QLabel(property_fee)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.is_paid_label = QtWidgets.QLabel(property_fee)
        self.is_paid_label.setGeometry(QtCore.QRect(60, 260, 231, 61))
        self.is_paid_label.setText("")
        self.is_paid_label.setObjectName("is_paid_label")
        self.building_id_comboBox = QtWidgets.QComboBox(property_fee)
        self.building_id_comboBox.setGeometry(QtCore.QRect(410, 110, 111, 22))
        self.building_id_comboBox.setObjectName("building_id_comboBox")
        self.house_id_comboBox = QtWidgets.QComboBox(property_fee)
        self.house_id_comboBox.setGeometry(QtCore.QRect(410, 180, 111, 22))
        self.house_id_comboBox.setObjectName("house_id_comboBox")
        self.paid_dateEdit = QtWidgets.QDateEdit(property_fee)
        self.paid_dateEdit.setGeometry(QtCore.QRect(160, 180, 110, 22))
        self.paid_dateEdit.setObjectName("paid_dateEdit")
        self.label_5 = QtWidgets.QLabel(property_fee)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 72, 15))
        self.label_5.setObjectName("label_5")
        self.due_payment_lineEdit = QtWidgets.QLineEdit(property_fee)
        self.due_payment_lineEdit.setGeometry(QtCore.QRect(160, 140, 113, 21))
        self.due_payment_lineEdit.setReadOnly(True)
        self.due_payment_lineEdit.setObjectName("due_payment_lineEdit")
        self.label_8 = QtWidgets.QLabel(property_fee)
        self.label_8.setGeometry(QtCore.QRect(340, 180, 72, 15))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(property_fee)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 72, 15))
        self.label_3.setObjectName("label_3")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(property_fee)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(160, 220, 113, 21))
        self.staff_id_lineEdit.setReadOnly(True)
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.label_6 = QtWidgets.QLabel(property_fee)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 72, 15))
        self.label_6.setObjectName("label_6")
        self.month_lineEdit = QtWidgets.QLineEdit(property_fee)
        self.month_lineEdit.setGeometry(QtCore.QRect(160, 100, 113, 21))
        self.month_lineEdit.setReadOnly(True)
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.label_7 = QtWidgets.QLabel(property_fee)
        self.label_7.setGeometry(QtCore.QRect(340, 110, 72, 15))
        self.label_7.setObjectName("label_7")
        self.year_lineEdit = QtWidgets.QLineEdit(property_fee)
        self.year_lineEdit.setGeometry(QtCore.QRect(160, 50, 113, 21))
        self.year_lineEdit.setReadOnly(True)
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.label = QtWidgets.QLabel(property_fee)
        self.label.setGeometry(QtCore.QRect(50, 50, 72, 15))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(property_fee)
        self.widget.setGeometry(QtCore.QRect(320, 260, 215, 85))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.new_pushButton = QtWidgets.QPushButton(self.widget)
        self.new_pushButton.setObjectName("new_pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.new_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(self.widget)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.exit_pushButton)

        self.retranslateUi(property_fee)
        self.exit_pushButton.clicked.connect(property_fee.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(property_fee)

    def retranslateUi(self, property_fee):
        _translate = QtCore.QCoreApplication.translate
        property_fee.setWindowTitle(_translate("property_fee", "property_fee"))
        self.label_2.setText(_translate("property_fee", "月"))
        self.label_5.setText(_translate("property_fee", "付费时间"))
        self.label_8.setText(_translate("property_fee", "房号"))
        self.label_3.setText(_translate("property_fee", "应付物业费"))
        self.label_6.setText(_translate("property_fee", "员工_id"))
        self.label_7.setText(_translate("property_fee", "楼号"))
        self.label.setText(_translate("property_fee", "年"))
        self.pushButton.setText(_translate("property_fee", "缴费"))
        self.new_pushButton.setText(_translate("property_fee", "刷新"))
        self.exit_pushButton.setText(_translate("property_fee", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    property_fee = QtWidgets.QWidget()
    ui = Ui_property_fee()
    ui.setupUi(property_fee)
    property_fee.show()
    sys.exit(app.exec_())
