# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_mianWind.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_mainWind(object):
    def setupUi(self, User_mainWind):
        User_mainWind.setObjectName("User_mainWind")
        User_mainWind.resize(905, 636)
        self.centralwidget = QtWidgets.QWidget(User_mainWind)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(160, 90, 611, 391))
        self.widget.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"background-image: url(:/images/images/background.jpeg);\n"
"border-radius:30px;")
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 611, 71))
        self.frame.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-radius:30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 20, 281, 31))
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Algerian\";")
        self.label.setObjectName("label")
        self.close_pushButton = QtWidgets.QPushButton(self.frame)
        self.close_pushButton.setGeometry(QtCore.QRect(540, 20, 61, 31))
        self.close_pushButton.setStyleSheet("border-image: url(:/icons/images/close.png);")
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.prpperty_fee_pushButton = QtWidgets.QPushButton(self.widget)
        self.prpperty_fee_pushButton.setGeometry(QtCore.QRect(80, 240, 161, 71))
        self.prpperty_fee_pushButton.setStyleSheet("font: 15pt \"Agency FB\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.prpperty_fee_pushButton.setObjectName("prpperty_fee_pushButton")
        self.parking_fee_pushButton = QtWidgets.QPushButton(self.widget)
        self.parking_fee_pushButton.setGeometry(QtCore.QRect(350, 240, 161, 71))
        self.parking_fee_pushButton.setStyleSheet("font: 15pt \"Agency FB\";\n"
"background-color:  rgb(255, 255, 255);")
        self.parking_fee_pushButton.setObjectName("parking_fee_pushButton")
        self.person_info_label = QtWidgets.QLabel(self.widget)
        self.person_info_label.setGeometry(QtCore.QRect(150, 90, 201, 31))
        self.person_info_label.setText("")
        self.person_info_label.setObjectName("person_info_label")
        User_mainWind.setCentralWidget(self.centralwidget)

        self.retranslateUi(User_mainWind)
        self.close_pushButton.clicked.connect(User_mainWind.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(User_mainWind)

    def retranslateUi(self, User_mainWind):
        _translate = QtCore.QCoreApplication.translate
        User_mainWind.setWindowTitle(_translate("User_mainWind", "User_mianWind"))
        self.label.setText(_translate("User_mainWind", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">欢迎来到用户管理系统</span></p></body></html>"))
        self.prpperty_fee_pushButton.setText(_translate("User_mainWind", "物业费缴费"))
        self.parking_fee_pushButton.setText(_translate("User_mainWind", "停车费缴费"))
import resource_user_ui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    User_mainWind = QtWidgets.QMainWindow()
    ui = Ui_User_mainWind()
    ui.setupUi(User_mainWind)
    User_mainWind.show()
    sys.exit(app.exec_())
