# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_parking_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_parking_fee(object):
    def setupUi(self, update_parking_fee):
        update_parking_fee.setObjectName("update_parking_fee")
        update_parking_fee.resize(400, 449)
        self.label_2 = QtWidgets.QLabel(update_parking_fee)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 72, 15))
        self.label_2.setObjectName("label_2")
        self.paid_lineEdit = QtWidgets.QLineEdit(update_parking_fee)
        self.paid_lineEdit.setGeometry(QtCore.QRect(180, 200, 113, 21))
        self.paid_lineEdit.setObjectName("paid_lineEdit")
        self.parking_id_comboBox = QtWidgets.QComboBox(update_parking_fee)
        self.parking_id_comboBox.setGeometry(QtCore.QRect(180, 30, 111, 22))
        self.parking_id_comboBox.setObjectName("parking_id_comboBox")
        self.is_paid_radioButton = QtWidgets.QRadioButton(update_parking_fee)
        self.is_paid_radioButton.setGeometry(QtCore.QRect(180, 340, 115, 19))
        self.is_paid_radioButton.setChecked(True)
        self.is_paid_radioButton.setObjectName("is_paid_radioButton")
        self.label = QtWidgets.QLabel(update_parking_fee)
        self.label.setGeometry(QtCore.QRect(60, 40, 72, 15))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(update_parking_fee)
        self.label_7.setGeometry(QtCore.QRect(60, 290, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(update_parking_fee)
        self.label_5.setGeometry(QtCore.QRect(60, 200, 72, 15))
        self.label_5.setObjectName("label_5")
        self.due_pay_lineEdit = QtWidgets.QLineEdit(update_parking_fee)
        self.due_pay_lineEdit.setGeometry(QtCore.QRect(180, 150, 113, 21))
        self.due_pay_lineEdit.setObjectName("due_pay_lineEdit")
        self.label_4 = QtWidgets.QLabel(update_parking_fee)
        self.label_4.setGeometry(QtCore.QRect(60, 160, 72, 15))
        self.label_4.setObjectName("label_4")
        self.year_lineEdit = QtWidgets.QLineEdit(update_parking_fee)
        self.year_lineEdit.setGeometry(QtCore.QRect(180, 70, 113, 21))
        self.year_lineEdit.setReadOnly(True)
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(update_parking_fee)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(180, 290, 113, 21))
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.label_3 = QtWidgets.QLabel(update_parking_fee)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 72, 15))
        self.label_3.setObjectName("label_3")
        self.month_lineEdit = QtWidgets.QLineEdit(update_parking_fee)
        self.month_lineEdit.setGeometry(QtCore.QRect(180, 110, 113, 21))
        self.month_lineEdit.setReadOnly(True)
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.label_6 = QtWidgets.QLabel(update_parking_fee)
        self.label_6.setGeometry(QtCore.QRect(60, 250, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(update_parking_fee)
        self.label_9.setGeometry(QtCore.QRect(60, 340, 72, 15))
        self.label_9.setObjectName("label_9")
        self.paid_dateEdit = QtWidgets.QDateEdit(update_parking_fee)
        self.paid_dateEdit.setGeometry(QtCore.QRect(180, 250, 110, 22))
        self.paid_dateEdit.setObjectName("paid_dateEdit")
        self.q = QtWidgets.QPushButton(update_parking_fee)
        self.q.setGeometry(QtCore.QRect(150, 460, 111, 28))
        self.q.setObjectName("q")
        self.pushButton = QtWidgets.QPushButton(update_parking_fee)
        self.pushButton.setGeometry(QtCore.QRect(160, 390, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(update_parking_fee)
        QtCore.QMetaObject.connectSlotsByName(update_parking_fee)

    def retranslateUi(self, update_parking_fee):
        _translate = QtCore.QCoreApplication.translate
        update_parking_fee.setWindowTitle(_translate("update_parking_fee", "update_parking_fee"))
        self.label_2.setText(_translate("update_parking_fee", "年"))
        self.is_paid_radioButton.setText(_translate("update_parking_fee", "是"))
        self.label.setText(_translate("update_parking_fee", "车位号"))
        self.label_7.setText(_translate("update_parking_fee", "员工_id"))
        self.label_5.setText(_translate("update_parking_fee", "实付车位费"))
        self.label_4.setText(_translate("update_parking_fee", "应付车位费"))
        self.label_3.setText(_translate("update_parking_fee", "月"))
        self.label_6.setText(_translate("update_parking_fee", "付款日期"))
        self.label_9.setText(_translate("update_parking_fee", "是否缴费"))
        self.q.setText(_translate("update_parking_fee", "确定"))
        self.pushButton.setText(_translate("update_parking_fee", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_parking_fee = QtWidgets.QWidget()
    ui = Ui_update_parking_fee()
    ui.setupUi(update_parking_fee)
    update_parking_fee.show()
    sys.exit(app.exec_())
