# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_property_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_property_fee(object):
    def setupUi(self, update_property_fee):
        update_property_fee.setObjectName("update_property_fee")
        update_property_fee.resize(577, 432)
        self.house_id_comboBox = QtWidgets.QComboBox(update_property_fee)
        self.house_id_comboBox.setGeometry(QtCore.QRect(410, 190, 111, 22))
        self.house_id_comboBox.setObjectName("house_id_comboBox")
        self.label_4 = QtWidgets.QLabel(update_property_fee)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 72, 15))
        self.label_4.setObjectName("label_4")
        self.paid_dateEdit = QtWidgets.QDateEdit(update_property_fee)
        self.paid_dateEdit.setGeometry(QtCore.QRect(160, 230, 110, 22))
        self.paid_dateEdit.setObjectName("paid_dateEdit")
        self.label_2 = QtWidgets.QLabel(update_property_fee)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 72, 15))
        self.label_2.setObjectName("label_2")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(update_property_fee)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(160, 270, 113, 21))
        self.staff_id_lineEdit.setReadOnly(True)
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.label_7 = QtWidgets.QLabel(update_property_fee)
        self.label_7.setGeometry(QtCore.QRect(340, 120, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(update_property_fee)
        self.label.setGeometry(QtCore.QRect(50, 60, 72, 15))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(update_property_fee)
        self.pushButton.setGeometry(QtCore.QRect(160, 360, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.due_payment_lineEdit = QtWidgets.QLineEdit(update_property_fee)
        self.due_payment_lineEdit.setGeometry(QtCore.QRect(160, 150, 113, 21))
        self.due_payment_lineEdit.setObjectName("due_payment_lineEdit")
        self.label_3 = QtWidgets.QLabel(update_property_fee)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(update_property_fee)
        self.label_6.setGeometry(QtCore.QRect(50, 280, 72, 15))
        self.label_6.setObjectName("label_6")
        self.building_id_comboBox = QtWidgets.QComboBox(update_property_fee)
        self.building_id_comboBox.setGeometry(QtCore.QRect(410, 120, 111, 22))
        self.building_id_comboBox.setObjectName("building_id_comboBox")
        self.label_5 = QtWidgets.QLabel(update_property_fee)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 72, 15))
        self.label_5.setObjectName("label_5")
        self.is_paid_radioButton = QtWidgets.QRadioButton(update_property_fee)
        self.is_paid_radioButton.setGeometry(QtCore.QRect(160, 320, 115, 19))
        self.is_paid_radioButton.setChecked(True)
        self.is_paid_radioButton.setObjectName("is_paid_radioButton")
        self.payment_lineEdit = QtWidgets.QLineEdit(update_property_fee)
        self.payment_lineEdit.setGeometry(QtCore.QRect(160, 190, 113, 21))
        self.payment_lineEdit.setObjectName("payment_lineEdit")
        self.label_8 = QtWidgets.QLabel(update_property_fee)
        self.label_8.setGeometry(QtCore.QRect(340, 190, 72, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(update_property_fee)
        self.label_9.setGeometry(QtCore.QRect(50, 320, 72, 15))
        self.label_9.setObjectName("label_9")
        self.month_lineEdit = QtWidgets.QLineEdit(update_property_fee)
        self.month_lineEdit.setGeometry(QtCore.QRect(160, 110, 113, 21))
        self.month_lineEdit.setReadOnly(True)
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.year_lineEdit = QtWidgets.QLineEdit(update_property_fee)
        self.year_lineEdit.setGeometry(QtCore.QRect(160, 60, 113, 21))
        self.year_lineEdit.setReadOnly(True)
        self.year_lineEdit.setObjectName("year_lineEdit")

        self.retranslateUi(update_property_fee)
        QtCore.QMetaObject.connectSlotsByName(update_property_fee)

    def retranslateUi(self, update_property_fee):
        _translate = QtCore.QCoreApplication.translate
        update_property_fee.setWindowTitle(_translate("update_property_fee", "update_property_fee"))
        self.label_4.setText(_translate("update_property_fee", "实付物业费"))
        self.label_2.setText(_translate("update_property_fee", "月"))
        self.label_7.setText(_translate("update_property_fee", "楼号"))
        self.label.setText(_translate("update_property_fee", "年"))
        self.pushButton.setText(_translate("update_property_fee", "确定"))
        self.label_3.setText(_translate("update_property_fee", "应付物业费"))
        self.label_6.setText(_translate("update_property_fee", "员工_id"))
        self.label_5.setText(_translate("update_property_fee", "付费时间"))
        self.is_paid_radioButton.setText(_translate("update_property_fee", "是"))
        self.label_8.setText(_translate("update_property_fee", "房号"))
        self.label_9.setText(_translate("update_property_fee", "是否缴费"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_property_fee = QtWidgets.QWidget()
    ui = Ui_update_property_fee()
    ui.setupUi(update_property_fee)
    update_property_fee.show()
    sys.exit(app.exec_())
