# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_building.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_building(object):
    def setupUi(self, update_building):
        update_building.setObjectName("update_building")
        update_building.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(update_building)
        self.pushButton.setGeometry(QtCore.QRect(160, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(update_building)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.building_id_lineEdit = QtWidgets.QLineEdit(update_building)
        self.building_id_lineEdit.setGeometry(QtCore.QRect(160, 60, 113, 21))
        self.building_id_lineEdit.setObjectName("building_id_lineEdit")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(update_building)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(160, 100, 113, 21))
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.label = QtWidgets.QLabel(update_building)
        self.label.setGeometry(QtCore.QRect(40, 60, 72, 15))
        self.label.setObjectName("label")

        self.retranslateUi(update_building)
        QtCore.QMetaObject.connectSlotsByName(update_building)

    def retranslateUi(self, update_building):
        _translate = QtCore.QCoreApplication.translate
        update_building.setWindowTitle(_translate("update_building", "Form"))
        self.pushButton.setText(_translate("update_building", "确定"))
        self.label_2.setText(_translate("update_building", "管理员工ID"))
        self.label.setText(_translate("update_building", "楼栋号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_building = QtWidgets.QWidget()
    ui = Ui_update_building()
    ui.setupUi(update_building)
    update_building.show()
    sys.exit(app.exec_())
