# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_parking_space.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_parking_space(object):
    def setupUi(self, update_parking_space):
        update_parking_space.setObjectName("update_parking_space")
        update_parking_space.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(update_parking_space)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.license = QtWidgets.QLineEdit(update_parking_space)
        self.license.setGeometry(QtCore.QRect(160, 160, 113, 21))
        self.license.setObjectName("license")
        self.pushButton = QtWidgets.QPushButton(update_parking_space)
        self.pushButton.setGeometry(QtCore.QRect(160, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.building_id = QtWidgets.QLineEdit(update_parking_space)
        self.building_id.setGeometry(QtCore.QRect(160, 80, 113, 21))
        self.building_id.setObjectName("building_id")
        self.label = QtWidgets.QLabel(update_parking_space)
        self.label.setGeometry(QtCore.QRect(50, 80, 72, 15))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(update_parking_space)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 72, 15))
        self.label_3.setObjectName("label_3")
        self.house_id = QtWidgets.QLineEdit(update_parking_space)
        self.house_id.setGeometry(QtCore.QRect(160, 120, 113, 21))
        self.house_id.setObjectName("house_id")
        self.parking_fee = QtWidgets.QLineEdit(update_parking_space)
        self.parking_fee.setGeometry(QtCore.QRect(160, 210, 113, 21))
        self.parking_fee.setObjectName("parking_fee")
        self.label_4 = QtWidgets.QLabel(update_parking_space)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(update_parking_space)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 72, 15))
        self.label_5.setObjectName("label_5")
        self.parking_space_id_lineEdit = QtWidgets.QLineEdit(update_parking_space)
        self.parking_space_id_lineEdit.setGeometry(QtCore.QRect(160, 40, 113, 21))
        self.parking_space_id_lineEdit.setObjectName("parking_space_id_lineEdit")

        self.retranslateUi(update_parking_space)
        QtCore.QMetaObject.connectSlotsByName(update_parking_space)

    def retranslateUi(self, update_parking_space):
        _translate = QtCore.QCoreApplication.translate
        update_parking_space.setWindowTitle(_translate("update_parking_space", "update_parking_space"))
        self.label_2.setText(_translate("update_parking_space", "房号"))
        self.pushButton.setText(_translate("update_parking_space", "确定"))
        self.label.setText(_translate("update_parking_space", "楼号"))
        self.label_3.setText(_translate("update_parking_space", "车牌号"))
        self.label_4.setText(_translate("update_parking_space", "停车费"))
        self.label_5.setText(_translate("update_parking_space", "车位编号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_parking_space = QtWidgets.QWidget()
    ui = Ui_update_parking_space()
    ui.setupUi(update_parking_space)
    update_parking_space.show()
    sys.exit(app.exec_())
