# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_staff_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_staff_info(object):
    def setupUi(self, update_staff_info):
        update_staff_info.setObjectName("update_staff_info")
        update_staff_info.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(update_staff_info)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.position_combox = QtWidgets.QComboBox(update_staff_info)
        self.position_combox.setGeometry(QtCore.QRect(140, 120, 111, 22))
        self.position_combox.setObjectName("position_combox")
        self.position_combox.addItem("")
        self.position_combox.addItem("")
        self.label = QtWidgets.QLabel(update_staff_info)
        self.label.setGeometry(QtCore.QRect(60, 120, 72, 15))
        self.label.setObjectName("label")
        self.name_editor = QtWidgets.QLineEdit(update_staff_info)
        self.name_editor.setGeometry(QtCore.QRect(140, 70, 113, 21))
        self.name_editor.setObjectName("name_editor")
        self.pushButton = QtWidgets.QPushButton(update_staff_info)
        self.pushButton.setGeometry(QtCore.QRect(140, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(update_staff_info)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 72, 15))
        self.label_3.setObjectName("label_3")
        self.password_lineEdit = QtWidgets.QLineEdit(update_staff_info)
        self.password_lineEdit.setGeometry(QtCore.QRect(140, 170, 113, 21))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.label_4 = QtWidgets.QLabel(update_staff_info)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 21, 16))
        self.label_4.setObjectName("label_4")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(update_staff_info)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(140, 20, 113, 21))
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")

        self.retranslateUi(update_staff_info)
        QtCore.QMetaObject.connectSlotsByName(update_staff_info)

    def retranslateUi(self, update_staff_info):
        _translate = QtCore.QCoreApplication.translate
        update_staff_info.setWindowTitle(_translate("update_staff_info", "update_staff_info"))
        self.label_2.setText(_translate("update_staff_info", "姓名"))
        self.position_combox.setItemText(0, _translate("update_staff_info", "普通员工"))
        self.position_combox.setItemText(1, _translate("update_staff_info", "管理员"))
        self.label.setText(_translate("update_staff_info", "职位"))
        self.pushButton.setText(_translate("update_staff_info", "确定"))
        self.label_3.setText(_translate("update_staff_info", "password"))
        self.label_4.setText(_translate("update_staff_info", "id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_staff_info = QtWidgets.QWidget()
    ui = Ui_update_staff_info()
    ui.setupUi(update_staff_info)
    update_staff_info.show()
    sys.exit(app.exec_())
