# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_parking_space.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_parking_space(object):
    def setupUi(self, register_parking_space):
        register_parking_space.setObjectName("register_parking_space")
        register_parking_space.resize(536, 300)
        self.label = QtWidgets.QLabel(register_parking_space)
        self.label.setGeometry(QtCore.QRect(40, 50, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_parking_space)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(register_parking_space)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(register_parking_space)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 72, 15))
        self.label_4.setObjectName("label_4")
        self.building_id = QtWidgets.QLineEdit(register_parking_space)
        self.building_id.setGeometry(QtCore.QRect(150, 50, 113, 21))
        self.building_id.setObjectName("building_id")
        self.house_id = QtWidgets.QLineEdit(register_parking_space)
        self.house_id.setGeometry(QtCore.QRect(150, 90, 113, 21))
        self.house_id.setObjectName("house_id")
        self.license = QtWidgets.QLineEdit(register_parking_space)
        self.license.setGeometry(QtCore.QRect(150, 140, 113, 21))
        self.license.setObjectName("license")
        self.parking_fee = QtWidgets.QLineEdit(register_parking_space)
        self.parking_fee.setGeometry(QtCore.QRect(150, 190, 113, 21))
        self.parking_fee.setObjectName("parking_fee")
        self.pushButton = QtWidgets.QPushButton(register_parking_space)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(register_parking_space)
        QtCore.QMetaObject.connectSlotsByName(register_parking_space)

    def retranslateUi(self, register_parking_space):
        _translate = QtCore.QCoreApplication.translate
        register_parking_space.setWindowTitle(_translate("register_parking_space", "register_space"))
        self.label.setText(_translate("register_parking_space", "楼号"))
        self.label_2.setText(_translate("register_parking_space", "房号"))
        self.label_3.setText(_translate("register_parking_space", "车牌号"))
        self.label_4.setText(_translate("register_parking_space", "停车费"))
        self.pushButton.setText(_translate("register_parking_space", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_parking_space = QtWidgets.QWidget()
    ui = Ui_register_parking_space()
    ui.setupUi(register_parking_space)
    register_parking_space.show()
    sys.exit(app.exec_())
