# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_staff(object):
    def setupUi(self, register_staff):
        register_staff.setObjectName("register_staff")
        register_staff.resize(400, 300)
        self.label = QtWidgets.QLabel(register_staff)
        self.label.setGeometry(QtCore.QRect(60, 120, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_staff)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 72, 15))
        self.label_2.setObjectName("label_2")
        self.name_editor = QtWidgets.QLineEdit(register_staff)
        self.name_editor.setGeometry(QtCore.QRect(140, 60, 113, 21))
        self.name_editor.setObjectName("name_editor")
        self.position_combox = QtWidgets.QComboBox(register_staff)
        self.position_combox.setGeometry(QtCore.QRect(140, 120, 111, 22))
        self.position_combox.setObjectName("position_combox")
        self.position_combox.addItem("")
        self.position_combox.addItem("")
        self.pushButton = QtWidgets.QPushButton(register_staff)
        self.pushButton.setGeometry(QtCore.QRect(140, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(register_staff)
        QtCore.QMetaObject.connectSlotsByName(register_staff)

    def retranslateUi(self, register_staff):
        _translate = QtCore.QCoreApplication.translate
        register_staff.setWindowTitle(_translate("register_staff", "register_staff"))
        self.label.setText(_translate("register_staff", "职位"))
        self.label_2.setText(_translate("register_staff", "姓名"))
        self.position_combox.setItemText(0, _translate("register_staff", "普通员工"))
        self.position_combox.setItemText(1, _translate("register_staff", "管理员"))
        self.pushButton.setText(_translate("register_staff", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_staff = QtWidgets.QWidget()
    ui = Ui_register_staff()
    ui.setupUi(register_staff)
    register_staff.show()
    sys.exit(app.exec_())
