# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_resident.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_resident(object):
    def setupUi(self, register_resident):
        register_resident.setObjectName("register_resident")
        register_resident.resize(400, 300)
        self.label_4 = QtWidgets.QLabel(register_resident)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 72, 15))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(register_resident)
        self.lineEdit.setGeometry(QtCore.QRect(190, 30, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(register_resident)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(register_resident)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(register_resident)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 110, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(register_resident)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 150, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(register_resident)
        self.label.setGeometry(QtCore.QRect(60, 30, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(register_resident)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 70, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(register_resident)
        self.pushButton.setGeometry(QtCore.QRect(190, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(register_resident)
        QtCore.QMetaObject.connectSlotsByName(register_resident)

    def retranslateUi(self, register_resident):
        _translate = QtCore.QCoreApplication.translate
        register_resident.setWindowTitle(_translate("register_resident", "Form"))
        self.label_4.setText(_translate("register_resident", "family_size"))
        self.label_3.setText(_translate("register_resident", "employer"))
        self.label_2.setText(_translate("register_resident", "name"))
        self.label.setText(_translate("register_resident", "email"))
        self.pushButton.setText(_translate("register_resident", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_resident = QtWidgets.QWidget()
    ui = Ui_register_resident()
    ui.setupUi(register_resident)
    register_resident.show()
    sys.exit(app.exec_())
