# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_parking_fees.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_parking_fees(object):
    def setupUi(self, register_parking_fees):
        register_parking_fees.setObjectName("register_parking_fees")
        register_parking_fees.resize(367, 436)
        self.label = QtWidgets.QLabel(register_parking_fees)
        self.label.setGeometry(QtCore.QRect(50, 60, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_parking_fees)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(register_parking_fees)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(register_parking_fees)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(register_parking_fees)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(register_parking_fees)
        self.label_6.setGeometry(QtCore.QRect(50, 270, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(register_parking_fees)
        self.label_7.setGeometry(QtCore.QRect(50, 310, 72, 15))
        self.label_7.setObjectName("label_7")
        self.parking_id_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.parking_id_lineEdit.setGeometry(QtCore.QRect(170, 50, 113, 21))
        self.parking_id_lineEdit.setObjectName("parking_id_lineEdit")
        self.year_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.year_lineEdit.setGeometry(QtCore.QRect(170, 90, 113, 21))
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.month_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.month_lineEdit.setGeometry(QtCore.QRect(170, 130, 113, 21))
        self.month_lineEdit.setObjectName("month_lineEdit")
        self.due_pay_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.due_pay_lineEdit.setGeometry(QtCore.QRect(170, 170, 113, 21))
        self.due_pay_lineEdit.setObjectName("due_pay_lineEdit")
        self.paid_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.paid_lineEdit.setGeometry(QtCore.QRect(170, 220, 113, 21))
        self.paid_lineEdit.setObjectName("paid_lineEdit")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(register_parking_fees)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(170, 310, 113, 21))
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.paid_dateEdit = QtWidgets.QDateEdit(register_parking_fees)
        self.paid_dateEdit.setGeometry(QtCore.QRect(170, 270, 110, 22))
        self.paid_dateEdit.setObjectName("paid_dateEdit")
        self.pushButton = QtWidgets.QPushButton(register_parking_fees)
        self.pushButton.setGeometry(QtCore.QRect(170, 360, 111, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(register_parking_fees)
        QtCore.QMetaObject.connectSlotsByName(register_parking_fees)

    def retranslateUi(self, register_parking_fees):
        _translate = QtCore.QCoreApplication.translate
        register_parking_fees.setWindowTitle(_translate("register_parking_fees", "Form"))
        self.label.setText(_translate("register_parking_fees", "车位号"))
        self.label_2.setText(_translate("register_parking_fees", "年"))
        self.label_3.setText(_translate("register_parking_fees", "月"))
        self.label_4.setText(_translate("register_parking_fees", "应付车位费"))
        self.label_5.setText(_translate("register_parking_fees", "实付车位费"))
        self.label_6.setText(_translate("register_parking_fees", "付款日期"))
        self.label_7.setText(_translate("register_parking_fees", "员工_id"))
        self.pushButton.setText(_translate("register_parking_fees", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_parking_fees = QtWidgets.QWidget()
    ui = Ui_register_parking_fees()
    ui.setupUi(register_parking_fees)
    register_parking_fees.show()
    sys.exit(app.exec_())
