# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_house.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_house(object):
    def setupUi(self, register_house):
        register_house.setObjectName("register_house")
        register_house.resize(400, 300)
        self.label = QtWidgets.QLabel(register_house)
        self.label.setGeometry(QtCore.QRect(60, 40, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_house)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(register_house)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 72, 15))
        self.label_3.setObjectName("label_3")
        self.building_id = QtWidgets.QLineEdit(register_house)
        self.building_id.setGeometry(QtCore.QRect(170, 40, 113, 21))
        self.building_id.setObjectName("building_id")
        self.area = QtWidgets.QLineEdit(register_house)
        self.area.setGeometry(QtCore.QRect(170, 90, 113, 21))
        self.area.setObjectName("area")
        self.resident_id = QtWidgets.QLineEdit(register_house)
        self.resident_id.setGeometry(QtCore.QRect(170, 140, 113, 21))
        self.resident_id.setObjectName("resident_id")
        self.pushButton = QtWidgets.QPushButton(register_house)
        self.pushButton.setGeometry(QtCore.QRect(70, 220, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(register_house)
        QtCore.QMetaObject.connectSlotsByName(register_house)

    def retranslateUi(self, register_house):
        _translate = QtCore.QCoreApplication.translate
        register_house.setWindowTitle(_translate("register_house", "register_house"))
        self.label.setText(_translate("register_house", "楼号"))
        self.label_2.setText(_translate("register_house", "面积"))
        self.label_3.setText(_translate("register_house", "住户编号"))
        self.pushButton.setText(_translate("register_house", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_house = QtWidgets.QWidget()
    ui = Ui_register_house()
    ui.setupUi(register_house)
    register_house.show()
    sys.exit(app.exec_())
