# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_del_staff(object):
    def setupUi(self, del_staff):
        del_staff.setObjectName("del_staff")
        del_staff.resize(400, 300)
        self.label = QtWidgets.QLabel(del_staff)
        self.label.setGeometry(QtCore.QRect(40, 40, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(del_staff)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 72, 15))
        self.label_2.setObjectName("label_2")
        self.staff_id_lineEdit = QtWidgets.QLineEdit(del_staff)
        self.staff_id_lineEdit.setGeometry(QtCore.QRect(140, 40, 113, 21))
        self.staff_id_lineEdit.setObjectName("staff_id_lineEdit")
        self.staff_name_lineEdit = QtWidgets.QLineEdit(del_staff)
        self.staff_name_lineEdit.setGeometry(QtCore.QRect(140, 90, 113, 21))
        self.staff_name_lineEdit.setObjectName("staff_name_lineEdit")
        self.pushButton = QtWidgets.QPushButton(del_staff)
        self.pushButton.setGeometry(QtCore.QRect(140, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(del_staff)
        QtCore.QMetaObject.connectSlotsByName(del_staff)

    def retranslateUi(self, del_staff):
        _translate = QtCore.QCoreApplication.translate
        del_staff.setWindowTitle(_translate("del_staff", "del_staff"))
        self.label.setText(_translate("del_staff", "员工编号"))
        self.label_2.setText(_translate("del_staff", "员工姓名"))
        self.pushButton.setText(_translate("del_staff", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    del_staff = QtWidgets.QWidget()
    ui = Ui_del_staff()
    ui.setupUi(del_staff)
    del_staff.show()
    sys.exit(app.exec_())
