# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def __init__(self):
        self.sig_up_btn = None
        self.login_btn = None
        self.password_editor = None
        self.id_editor = None
        self.password_label = None
        self.id_label = None
        self.login_label = None

    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(400, 300)
        self.login_label = QtWidgets.QLabel(login)
        self.login_label.setGeometry(QtCore.QRect(170, 30, 72, 15))
        self.login_label.setObjectName("login_label")
        self.id_label = QtWidgets.QLabel(login)
        self.id_label.setGeometry(QtCore.QRect(31, 90, 101, 20))
        self.id_label.setObjectName("id_label")
        self.password_label = QtWidgets.QLabel(login)
        self.password_label.setGeometry(QtCore.QRect(30, 140, 101, 16))
        self.password_label.setObjectName("password_label")
        self.id_editor = QtWidgets.QLineEdit(login)
        self.id_editor.setGeometry(QtCore.QRect(140, 90, 171, 21))
        self.id_editor.setObjectName("id_editor")
        self.password_editor = QtWidgets.QLineEdit(login)
        self.password_editor.setGeometry(QtCore.QRect(140, 140, 171, 21))
        self.password_editor.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_editor.setObjectName("password_editor")
        self.login_btn = QtWidgets.QPushButton(login)
        self.login_btn.setGeometry(QtCore.QRect(60, 210, 93, 28))
        self.login_btn.setObjectName("login_btn")
        self.sig_up_btn = QtWidgets.QPushButton(login)
        self.sig_up_btn.setGeometry(QtCore.QRect(210, 210, 93, 28))
        self.sig_up_btn.setObjectName("sig_up_btn")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.login_label.setText(_translate("login", "LOGIN"))
        self.id_label.setText(_translate("login", "property_id:"))
        self.password_label.setText(_translate("login", "password:"))
        self.login_btn.setText(_translate("login", "log in"))
        self.sig_up_btn.setText(_translate("login", "sig up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QWidget()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
