# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reminder_fee.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reminder_fee(object):
    def setupUi(self, reminder_fee):
        reminder_fee.setObjectName("reminder_fee")
        reminder_fee.resize(815, 527)
        self.today_dateEdit = QtWidgets.QDateEdit(reminder_fee)
        self.today_dateEdit.setGeometry(QtCore.QRect(90, 438, 110, 22))
        self.today_dateEdit.setObjectName("today_dateEdit")
        self.label = QtWidgets.QLabel(reminder_fee)
        self.label.setGeometry(QtCore.QRect(13, 440, 61, 20))
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(reminder_fee)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 741, 401))
        self.tableView.setObjectName("tableView")
        self.query_not_paid_btn = QtWidgets.QPushButton(reminder_fee)
        self.query_not_paid_btn.setGeometry(QtCore.QRect(390, 440, 121, 23))
        self.query_not_paid_btn.setObjectName("query_not_paid_btn")
        self.reminder_pay_btn = QtWidgets.QPushButton(reminder_fee)
        self.reminder_pay_btn.setGeometry(QtCore.QRect(590, 440, 151, 23))
        self.reminder_pay_btn.setObjectName("reminder_pay_btn")
        self.fee_species_comboBox = QtWidgets.QComboBox(reminder_fee)
        self.fee_species_comboBox.setGeometry(QtCore.QRect(240, 440, 87, 22))
        self.fee_species_comboBox.setObjectName("fee_species_comboBox")
        self.fee_species_comboBox.addItem("")
        self.fee_species_comboBox.addItem("")

        self.retranslateUi(reminder_fee)
        QtCore.QMetaObject.connectSlotsByName(reminder_fee)

    def retranslateUi(self, reminder_fee):
        _translate = QtCore.QCoreApplication.translate
        reminder_fee.setWindowTitle(_translate("reminder_fee", "reminder_fee"))
        self.label.setText(_translate("reminder_fee", "当前日期"))
        self.query_not_paid_btn.setText(_translate("reminder_fee", "查询未缴费名单"))
        self.reminder_pay_btn.setText(_translate("reminder_fee", "用email提醒业主缴费"))
        self.fee_species_comboBox.setItemText(0, _translate("reminder_fee", "物业费"))
        self.fee_species_comboBox.setItemText(1, _translate("reminder_fee", "停车费"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reminder_fee = QtWidgets.QWidget()
    ui = Ui_reminder_fee()
    ui.setupUi(reminder_fee)
    reminder_fee.show()
    sys.exit(app.exec_())
